export const treeDataElements = [
  {
    key: new Date().toISOString() + "2",
    title: "{{twoBlocks}}",
    value:
      '<table align="center" border="0" bgcolor="#ffffff" class="mlContentTable mlContentTableDefault" cellpadding="0" cellspacing="0" width="640">\n    <tbody><tr>\n      <td class="mlContentTableCardTd">\n        <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" class="mlContentTable ml-default" style="width: 640px; min-width: 640px;" width="640">\n          <tbody><tr>\n            <td>\n              <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="640" style="width: 640px; min-width: 640px;" class="mlContentTable">\n                <tbody><tr>\n                  <td height="20" class="spacingHeight-20" style="line-height: 20px; min-height: 20px;"></td>\n                </tr>\n              </tbody></table>\n              <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="640" style="width: 640px; min-width: 640px;" class="mlContentTable">\n                <tbody><tr>\n                  <td align="center" style="padding: 0px 40px;" class="mlContentOuter">\n                    <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="100%">\n                      <tbody><tr>\n                        <td height="20" class="spacingHeight-20"></td>\n                      </tr>\n                    </tbody></table>\n                    <table role="presentation" cellpadding="0" border="0" align="center" width="100%">\n                      <tbody><tr>\n                        <td valign="top">\n                          {{item1}}\n                          <!--[if mso]>\n                        </td>\n                        <td valign="top">\n                        <![endif]-->\n                        {{item2}}\n                        </td>\n                      </tr>\n                    </tbody></table>\n                  </td>\n                </tr>\n              </tbody></table>\n              <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="640" style="width: 640px; min-width: 640px;" class="mlContentTable">\n                <tbody><tr>\n                  <td height="20" class="spacingHeight-20"></td>\n                </tr>\n              </tbody></table>\n              <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="640" style="width: 640px; min-width: 640px;" class="mlContentTable">\n                <tbody><tr>\n                  <td align="center" style="padding: 0px 40px;" class="mlContentOuter"></td>\n                </tr>\n              </tbody></table>\n            </td>\n          </tr>\n        </tbody></table>\n      </td>\n    </tr>\n  </tbody></table>',
    children: [],
  },
  {
    key: new Date().toISOString() + "3",
    title: "{{itemWithImageTitleSubtitleLeft}}",
    value:
      '<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="left" width="267" class="mlContentTable marginBottom" style="width: 267px; min-width: 267px;">\n    <tbody><tr>\n      <td id="imageBlock-14" align="center">\n        <a href="{{link}}" data-link-id="960357277" target="_self">\n\n<img src="{{image}}" border="0" alt="" width="267" style="display: block;">\n\n</a>\n      </td>\n    </tr>\n    <tr>\n      <td align="center" style="padding: 0px 20px;">\n        <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="100%">\n          <tbody><tr>\n            <td height="20" class="spacingHeight-20"></td>\n          </tr>\n          <tr>\n            <td align="left" class="bodyTitle" id="bodyText-14" style="font-family: &#39;Poppins&#39;, sans-serif; font-size: 14px; line-height: 150%; color: #6f6f6f;">\n              <p style="margin-top: 0px; margin-bottom: 0px; line-height: 150%; text-align: center;"><strong></strong><strong><span style="font-size: 16px;">{{title}}</span></strong><br>{{subtitle}}</p>\n            </td>\n          </tr>\n        </tbody></table>\n      </td>\n    </tr>\n  </tbody></table>',
    children: [],
  },
  {
    key: new Date().toISOString() + "4",
    title: "{{itemWithImageTitleSubtitleRight}}",
    value:
      '<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="right" width="267" class="mlContentTable" style="width: 267px; min-width: 267px;">\n    <tbody><tr>\n      <td id="imageBlock-15" align="center">\n        <a href="{{link}}" data-link-id="960357279" target="_self">\n\n<img src="{{image}}" border="0" alt="" width="267" style="display: block;">\n\n</a>\n      </td>\n    </tr>\n    <tr>\n      <td align="center" style="padding: 0px 20px;">\n        <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="100%">\n          <tbody><tr>\n            <td height="20" class="spacingHeight-20"></td>\n          </tr>\n          <tr>\n            <td align="left" class="bodyTitle" id="bodyText-15" style="font-family: &#39;Poppins&#39;, sans-serif; font-size: 14px; line-height: 150%; color: #6f6f6f;">\n              <p style="margin-top: 0px; margin-bottom: 0px; line-height: 150%; text-align: center;"><strong><span style="font-size: 16px;">{{title}}</span></strong><br>{{subtitle}}</p>\n            </td>\n          </tr>\n        </tbody></table>\n      </td>\n    </tr>\n  </tbody></table>',
    children: [],
  },
];
